### ISSUE TITLE
Calling function with an inline-allocated weakref parameter holds onto target object 

### ISSUE THREAD

**Issue by tinyg** [IronLanguages/ironpython2#273] opened 2017-11-26 23:58 UTC
If you run the following script, you will see that 

```
import weakref
import gc

class A():
    def __init__(self, test):
        self.test = test
    
    def __del__(self):
        print "__del__ " + str(self.test)

# show odd behaviour of weakrefs passed to functions holding item 
print "test 4"
def test4(b):
    print "'__del__ 4' should be printed after here but isnt"
    gc.collect(2)
    print "'__del__ 4' should be printed before here but isnt"

test4(weakref.ref(A(4)))
gc.collect(2)
print "'__del__ 4' still not printed even in the outer scope after a gc"

# and then show that weakrefs stored in variables and then passed to functions dont hold onto the weakref target
print "test 5"
def test5(b):
    print "'__del__ 5' is printed after here as expected (but so is 4)"
    gc.collect(2)
    print "'__del__ 5' is printed before here as expected"

r = weakref.ref(A(5))
test5(r)
```

One would expect A(4) to be finalised inside the function (since nothing should have a reference to it at that point). It then takes 2 additional garbage collects to free A(4)

If you put the weakref into a variable before then calling the function, it works as expected.

**Comment by slozier** [comment] 2017-11-27 13:46
See https://github.com/IronLanguages/ironpython2/pull/269#discussion_r152788623 for initial discussion.

**Comment by slozier** [comment] 2017-12-14 15:55
It looks like the object is held alive by the interpreter stack. This means the issue is not specific to `weakref`. Here's some repro code which doesn't involve `weakref`:
```Python
def test():
    class A(object):
        cnt = 0
        def __init__(self):
            A.cnt += 1    
        def __del__(self):
            A.cnt -= 1

    def test(x): pass

    test(test(test(A()))) # places an instance of A on the interpreter stack
    gc.collect()
    assert A.cnt == 1 # should be 0

    test(test(0)) # doesn't override the instance of A held by the interpreter stack
    gc.collect()
    assert A.cnt == 1 # should be 0

    test(test(test(0))) # overrides the instance of A held by the interpreter stack
    gc.collect()
    assert A.cnt == 0 
```

The issue could be resolved by "flushing" the stack on [Pop](https://github.com/IronLanguages/dlr/blob/7b1136127590f03c3d7b5d8580e51680e41f2ec9/Src/Microsoft.Dynamic/Interpreter/InterpretedFrame.cs#L92) and on `Pop(n)`. Something like:
```C#
public object Pop() {
    var val = Data[--StackIndex];
    Data[StackIndex] = null;
    return val;
}

public object Pop(int n) {
    StackIndex -= n;
    var val = Data[StackIndex];
    Array.Clear(Data, StackIndex, n);
    return val;
}
```

**Closed** 2018-01-03 18:41 UTC
