### ISSUE TITLE
distutils setup fails immediately

### ISSUE THREAD

**Issue by donboll** [IronLanguages/ironpython2#744] opened 2020-09-21 19:28 UTC
### Prerequisites

The issue tracker is used to report bugs and request new features, NOT to ask questions.

Questions should be posted to the users mailing list which can be accessed at 
https://ironpython.groups.io/g/users. 

* [ yes] Are you running the latest version?
* [ yes] Are you reporting to the correct repository?
* [ yes] Did you perform a cursory search?

### Description

'ipy setup install' does not work, gets an exception.

### Steps to Reproduce

ipy
>>> from setuptools import setup

Note, no external files invoked, simply importing setuptools triggers the error (see below)

**Expected behavior:** [What you expected to happen]
Expected to import the setup function from distutils, not raise an exception

**Actual behavior:** [What actually happened]
/cygdrive/c/don/work/oom/code/gitstuff/ipy/oom:ipy
IronPython 2.7.10 (2.7.10.1000)
[.NETFramework,Version=v4.5 on .NET Framework 4.8.4220.0 (64-bit)]
Type "help", "copyright", "credits" or "license" for more information.
>>> from setuptools import setup
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\setuptools\__init__.py
", line 151, in <module>
TypeError: a new-style class can't have only classic bases
>>>

### Versions

See above, IronPython 2.7.10 (2.7.10.1000).  Note, just installed the latest version, using .msi.  No tweaking, no other packages installed.  'ipy setup.py install' fails out of the box.

**Comment by slozier** [comment] 2020-09-21 19:58
Duplicate of https://github.com/IronLanguages/ironpython2/issues/624. Try using 2.7.11-rc1 instead https://github.com/IronLanguages/ironpython2/releases/tag/ipy-2.7.11-candidate1

**Comment by donboll** [comment] 2020-09-21 22:38
Thanks, ipy-2.7.11-candidate1 took care of the issue.

**Closed** 2020-09-21 22:46 UTC
