### ISSUE TITLE
Installing packagaes throws exception

### ISSUE THREAD

**Issue by Prodigio** [IronLanguages/ironpython2#230] opened 2017-08-11 12:05 UTC
I was trying to install a package with PTVS in Visual Studio 2017. Unfortunately it doesn't work.

In windows command line this command `ipy -X:Frames -m pip install martypy` thorws the same exception.

```> ----- Installing 'martypy' -----
> Collecting martypy
> C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:1: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
>   from __future__ import absolute_import
> C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py:1: SubjectAltNameWarning: Certificate for pypi.python.org has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
>   from __future__ import absolute_import
> Exception:
> Traceback (most recent call last):
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\basecommand.py", line 209, in main
>     status = self.run(options, args)
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\commands\install.py", line 299, in run
>     requirement_set.prepare_files(finder)
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\req\req_set.py", line 356, in prepare_files
>     discovered_reqs.extend(self._prepare_file(
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\contextlib.py", line 35, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\utils\logging.py", line 36, in indent_log
>     yield
> ValueError: too many values to unpack
> ----- Successfully installed 'martypy' -----```

**Comment by slide** [comment] 2017-12-05 14:56
This looks like a duplicate of #57

**Closed** 2017-12-05 14:57 UTC
