### ISSUE TITLE
`docutils` crashes IronPython 2.7.9rc1 with `StackOverflowException`

### ISSUE THREAD

**Issue by pekkaklarck** [IronLanguages/ironpython2#506] opened 2018-09-03 05:55 UTC
Trying to parse anything more complicated than `hello` with `docutils` crashes the whole IronPython 2.7.9rc1:

```python
IronPython 2.7.9rc1 (2.7.9.0) on .NET 4.0.30319.42000 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> from docutils.core import publish_doctree
>>> publish_doctree('hello')
<document: <paragraph...>>
>>> publish_doctree('hello\n-----\n')

Process is terminated due to StackOverflowException.
```

I'm fairly certain `docutils` worked fine with IronPython 2.7.8, but it wasn't possible to install 2.7.9rc1 along with it so don't have that version available anymore.

**Comment by slozier** [comment] 2018-09-03 11:50
Duplicate of https://github.com/IronLanguages/ironpython2/issues/113

**Closed by slozier** 2018-09-03 11:50 UTC

**Comment by pekkaklarck** [comment] 2018-09-03 18:31
Oh, apparently `docutils` didn't work earlier either....... Had totally forgotten I had submitted an issue about it (should have searched...) and not having an earlier version available made it impossible to test that. Sorry for the noise.
