### ISSUE TITLE
How to install numpy ,scipy and xlrd&xlwt&xlutils in ironPython 2.7.4 x64 ?

### ISSUE THREAD

**Issue by 1990chs** [IronLanguages/ironpython2#774] opened 2021-02-15 13:09 UTC

**Comment by slozier** [comment] 2021-02-16 14:25
Unfortunately numpy and scipy are not supported with IronPython. You can try the instructions at https://stackoverflow.com/questions/29397540/how-to-install-numpy-and-scipy-for-ironpython27-old-method-doesnt-work which may or may not work. Closing since it's a duplicate of https://github.com/IronLanguages/ironpython2/issues/587.

**Closed by slozier** 2021-02-16 14:25 UTC
