### ISSUE TITLE
`__eq__` of str subclasses does not have precedence when comparing with strings

### ISSUE THREAD

**Issue by slozier** [IronLanguages/ironpython2#482] opened 2018-08-02 18:06 UTC
The following test case fails:
```Python
class test(str):
    def __eq__(self, other):
        return True

assert "a" == test("b")
```

May be related to https://github.com/IronLanguages/ironpython2/issues/34

**Comment by slide** [comment] 2018-08-02 23:54
We currently don't handle the exception below (from https://docs.python.org/release/2.7.15/reference/datamodel.html#coercion-rules)

```
For objects x and y, first x.__op__(y) is tried. If this is not implemented or returns NotImplemented, y.__rop__(x) is tried. If this is also not implemented or returns NotImplemented, a TypeError exception is raised. But see the following exception:

Exception to the previous item: if the left operand is an instance of a built-in type or a 
new-style class, and the right operand is an instance of a proper subclass of that type
 or class and overrides the base’s __rop__() method, the right operand’s __rop__() 
method is tried before the left operand’s __op__() method.
```

**Comment by slide** [comment] 2018-08-02 23:57
I think this is a duplicate of #34 because OrderedDict is considered a new-style class.

**Comment by slide** [comment] 2018-08-03 00:01
Relevant: https://github.com/IronLanguages/main/pull/1174

**Closed** 2018-08-03 16:14 UTC
