### ISSUE TITLE
IronPython.Runtime.Exceptions.TypeErrorException:“not expecting type '<type 'bytes'>'”

### ISSUE THREAD

**Issue by lidong-dev** [IronLanguages/ironpython2#770] opened 2021-01-25 01:04 UTC
1.vs2019
2.IronPython:2.7.11
3.python file
```Python
# -*- coding:utf-8 -*-
import sys
sys.path.append(r'C:\Python27')
sys.path.append(r'C:\Python27\Lib\DLLs')
sys.path.append(r'C:\Python27\Lib')
sys.path.append(r'C:\Python27\Lib\site-packages')
sys.path.append(r'C:\Python27\Lib\site-packages\idna-2.10-py2.7.egg')
sys.path.append(r'C:\Python27\Lib\site-packages\chardet-4.0.0-py2.7.egg')
sys.path.append(r'C:\Python27\Lib\site-packages\certifi-2020.12.5-py2.7.egg')
sys.path.append(r'C:\Python27\Lib\site-packages\urllib3-1.26.2-py2.7.egg')
sys.path.append(r'C:\Python27\Lib\site-packages\requests-2.25.1-py2.7.egg')
import requests

def text():
	return "myresult"			
def getPageIps(url="http://www.faps.com.cn:8080/history.json"):
	headers={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; WOW64)"}
	r = requests.get(url,timeout=10)	    
	return r.text.encode('utf-8')
```
4. C# code
```C#
  var options = new Dictionary<string, object>();
            options["Frames"] = true;
            options["FullFrames"] = true;
            ScriptRuntime pyRuntime = Python.CreateRuntime(options);
            dynamic py = pyRuntime.UseFile("mainwindows.py");
            string a = py.getPageIps();
            Console.WriteLine(a);
            Console.ReadKey();
```
5.Exception 
>IronPython.Runtime.Exceptions.TypeErrorException:“not expecting type '<type 'bytes'>'”

**Comment by slozier** [comment] 2021-01-25 14:50
Duplicate of https://github.com/IronLanguages/ironpython2/issues/758. The suggested solution is to use an older version of requests (for example 2.18.4).

**Closed by slozier** 2021-01-25 14:50 UTC
