### ISSUE TITLE
weakref.ref object sometimes returns None in a mulithreaded scenario

### ISSUE THREAD

**Issue by slide** [IronLanguages/ironpython2#210] opened 2017-07-13 15:07 UTC
_From @TI-AviBerko on July 13, 2017 14:54_

weakref.ref object sometimes returns None in a mulithreades scenario.

I discovered this when using the RPyC library, a NetRef object holds a weakref to it's parent connection, then sometimes the weakref object returns None.
I modified the code a bit to make sure every strong object is perminently stored in a list for the duration of the test and still have the same issue.

(This was recreated with IPy 2.7.4 and 2.7.7, on 2 different PCs)

I managed to recreate the problem with this code:

```Python
import threading
import weakref
import os
from time import sleep


class Test(object):
    def test(self):
        return Test2(weakref.ref(self))

        
class Test2(object):
    def __init__(self, x):
        self._x = x
        

def target(i):
    print i
    t = Test()
    x = t.test()
    sleep(1)

    if x._x() is None:        
        print "x was none"
        os._exit(1)

ths = []
j = 0

while True:
    for i in xrange(20):
        th = threading.Thread(target=target, args=(j + i,))
        th.start()
        ths.append(th)
        
    j += i
    
    for th in ths:
        th.join()
```

_Copied from original issue: IronLanguages/main#1668_

**Comment by TI-AviBerko** [comment] 2017-07-13 15:31
That was quick. what happened to the original issue?

**Comment by slozier** [comment] 2017-07-13 15:32
The issue was just moved to the ironpython2 repo (main is no longer active).

**Comment by TI-AviBerko** [comment] 2017-07-13 15:36
I see. thanks.

I've been debugging this issue for around 2 days (on and off), as the original code doesn't always recreate it.
There's another weird thing that happens, if you try to print "t" ( `print "x was none", t` ), the bug doesn't manifest.

**Comment by slozier** [comment] 2017-07-13 20:02
Based on your sample code it looks like you're experiencing the effects of the .NET GC. The reason the bug doesn't manifest when you add `t` to print is that when you do that you're preventing the GC from collecting it (because it will need it for the print).

Here's a simplified example:
```Python
import gc
import weakref

class Obj(object): pass

def test2(i):
    print(i)
    t = Obj()
    w = weakref.ref(t)
    # t is no longer referenced from this point on and may be GCed!
    gc.collect()
    return w() is None

i = 0
while True:
    if test2(i):
        print("fail!")
        break
    i += 1
```

To be more in line with what Python does I imagine we would need to somehow maintain the reference to the end of the block?

**Comment by TI-AviBerko** [comment] 2017-07-13 20:12
@slozier 

I originally found the issue in code that is more like the example I gave, where a parent instance spawns another object that has a weakref to the parent, and even though the parent is still alive, the weakref is gone.

I don't think it's the same issue, if you run my example in a single thread you don't get the same problem.

**Comment by slozier** [comment] 2017-07-13 20:27
My example is just your example in a single thread and cleaned up a little:
```Python
import weakref
import os

class Test(object):
    def test(self):
        return Test2(weakref.ref(self))

class Test2(object):
    def __init__(self, x):
        self._x = x

def target(i):
    print i
    t = Test()
    x = t.test()
    # t is not longer used after this, it may be GCed!
    for _ in range(10000):
        _ = object()
    if x._x() is None:        
        print "x was none"
        os._exit(1)

j = 0

while True:
    target(j)
    j += 1    
```

**Comment by TI-AviBerko** [comment] 2017-07-13 20:43
I'm not sure this represents the issue I'm having with RPyC.

In RPyC, a Connection object is created by the server per connection, then this Connection object has a factory that spits out NetRef objects with a weakref to itself (the Connection() object).

Then sometimes a NetRef loses it's weakref to Connection object even though it's still active, it's __del__ isn't called and I even modified the code to store it in a list, and even though the weakref goes away.

**Comment by TI-AviBerko** [comment] 2017-07-13 20:45
The "block/scope" issue does look real though, since the name/variable still exists

**Comment by slozier** [comment] 2017-07-13 22:00
It's entirely possible the issue is something else. But in the case of your sample code it's exactly what happens. Maybe you could try posting a repro which uses RPyC?

**Comment by TI-AviBerko** [comment] 2017-07-14 03:59
Gist:
server: <script src="https://gist.github.com/TI-AviBerko/f77f570e198ccf419eea563b2a82012d.js"></script>
client: <script src="https://gist.github.com/TI-AviBerko/cab576019213fc5307471ac5b450e540.js"</script>

Note: there's an issue with itertools.count I discovered a while ago and it needs to be overridden with a thread safe version, RPyC uses it to generate sequence numbers and fails with ipy's version when multithreaded.

The issue is elusive, it may take quite a few runs for it to show up, it's frustrating actually...

The traceback I get for this code is:
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\Avi\Desktop\IronPython-2.7.4\Lib\threading.py", line 552, in _Thread__bootstrap_inner
    self.run()
  File "C:\Users\Avi\Desktop\IronPython-2.7.4\Lib\threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "server.py", line 51, in _
    cb(self._i)
  File "c:\python27\lib\site-packages\rpyc\core\netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "c:\python27\lib\site-packages\rpyc\core\netref.py", line 67, in syncreq
    conn = object.__getattribute__(proxy, "____conn__")()
ReferenceError: weak object has gone away

**Comment by slozier** [comment] 2017-07-14 13:24
Haven't been able to hit it, does it occur in the client or server? (Note that I'm trying with 2.7.7)

**Comment by TI-AviBerko** [comment] 2017-07-14 15:14
It occurs on the server side. I've been able to hit with 2.7.7 too, but it started with 2.7.4

It's not guaranteed to fail, you may have to run it several times in the course of a few hours.

**Comment by TI-AviBerko** [comment] 2017-07-16 13:16
There might be other issues at play here, this code doesn't work right on CPython, it gets stuck after a few iterations.
Since it doesn't get stuck on IronPython I suppose it has something to do with the GIL or some implementation issue in RPyC itself.
I opened an issue for this (not weakref related): https://github.com/tomerfiliba/rpyc/issues/223

**Comment by TI-AviBerko** [comment] 2017-07-24 10:40
@slozier, with the help of a RPyC maintainer, we managed to realized the problem was in the way I was calling async functions (concerning the RPyC client code), which would lead to weakref issues with a slightly different outcode on CPython.
It looks like the code is also stable now on IronPython, considering I haven't hit the issue yet.

Concerning the scope/block issue in my first example, it does deviate from CPython behavior though I guess it's a bit contrived.
If the weakref is local never used again then it's probably fine to let the GC do it's thing.

**Comment by slozier** [comment] 2017-07-24 13:25
@TI-AviBerko Glad you could work it out.

I'm closing the issue. While it does deviate from CPython, this type of GC difference is to be expected.

**Closed by slozier** 2017-07-24 13:25 UTC
Labels: confirmed
