### ISSUE TITLE
Ironpython has problems about some python-native libs and pyd problems.

### ISSUE THREAD

**Issue by delfinoA** [IronLanguages/ironpython2#463] opened 2018-07-17 14:21 UTC
Recently, we've been working on making our old python code compatible with IronPython which uses some native python libs, such as plist-lib, sqlite3 and others. We noticed that IronPython has less efficiency than native-python code called by C/C++. Especially , the sqlite3, which would take 4 time as long to insert 1M records, compaired with code called by C++.
We are also working on handle some iOS files on PC and Plist-lib is necessary, but it will not working with IronPython as XML-lib always cause a crash. I'm wodering if there will be a way to handle those problems? and may be we can fixed it by our own under your guidance.
thanks

**Comment by slide** [comment] 2018-07-17 14:24
The implementation of sqlite is written in C# on IronPython, it has not seen a lot of optimization, so I am not surprised by it being slower than the C implementation. This is something we would have to look at.

Can you give a test case for plistlib so we can see what the issue is?

**Comment by slozier** [comment] 2018-07-17 14:40
@slide plistlib uses expat so https://github.com/IronLanguages/ironpython2/pull/460 may fix the issue.

**Comment by delfinoA** [comment] 2018-07-17 14:41
Thanks for your answer！
Here is a simple plist file content, you can copy it into a text-file.
==========begin of the file=============
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array/>
</plist>
==========end of the file==============
When I use built-in plistlib , error happens:
>>> res = plistlib.readPlist('LoCoLastUnUploadDic.plist')                                                               Traceback (most recent call last):                                                                                        File "<stdin>", line 1, in <module>                                                                                     File "C:\Program Files\IronPython 2.7\Lib\plistlib.py", line 78, in readPlist                                           File "C:\Program Files\IronPython 2.7\Lib\plistlib.py", line 401, in parse                                            ImportError: cannot import expat from xml.parsers    
It seems like xml-lib caused the error.

**Comment by slide** [comment] 2018-07-17 15:01
Ok, this should be fixed with the PR that I currently have open that will incorporate an implementation of pyexpat by @slozier. I'll test out with the file you provided

**Comment by slide** [comment] 2018-07-18 12:57
I just ran a quick test and it looks like plistlib works with #460

**Closed** 2018-07-18 17:33 UTC
