### ISSUE TITLE
ValueError: too many values to unpack. Installing any package with pip.

### ISSUE THREAD

**Issue by JackandJazz** [IronLanguages/ironpython2#285] opened 2017-12-05 01:11 UTC
Hi there guys, Im getting this error while trying to install ANY package with pip.

I have checked all the internet and havent found a solution for this. May be pretty simple cause Im pretty new to programming in general but I really cant find a solution. Thanks ;)

example: ipy -X:Frames -m pip install numpy

Exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\commands\install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\req\req_set.py", line 356, in prepare_files
    discovered_reqs.extend(self._prepare_file(
  File "C:\Program Files (x86)\IronPython 2.7\Lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\utils\logging.py", line 36, in indent_log
    yield
ValueError: too many values to unpack

**Comment by slide** [comment] 2017-12-05 01:38
Can you try with the 2.7.8 beta?

**Comment by JackandJazz** [comment] 2017-12-05 01:49
Thanks for you answer. Where can I find it? It doesnt seem to be available for download in http://ironpython.net/

**Comment by slide** [comment] 2017-12-05 01:58
https://github.com/IronLanguages/ironpython2/releases/tag/ipy-2.7.8-beta1

**Comment by JackandJazz** [comment] 2017-12-05 02:28
No differences noticed. The only thing is the instalation folder (Program Files vs Program Files (x86)) Also two warmings appear. 


C:\WINDOWS\system32>ipy -X:Frames -m pip install numpy


Collecting numpy
C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:1: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  from __future__ import absolute_import
C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py:1: SubjectAltNameWarning: Certificate for pypi.python.org has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  from __future__ import absolute_import
Exception:
Traceback (most recent call last):
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\commands\install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\req\req_set.py", line 356, in prepare_files
    discovered_reqs.extend(self._prepare_file(
  File "C:\Program Files\IronPython 2.7\Lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\utils\logging.py", line 36, in indent_log
    yield
ValueError: too many values to unpack

**Comment by slide** [comment] 2017-12-05 14:55
This looks like a duplicate of #57

**Closed by slide** 2017-12-05 14:55 UTC

**Comment by slozier** [comment] 2017-12-05 19:05
@JackandJazz I believe we have identified the issue with the pip installer. You can try the build at https://ci.appveyor.com/project/AlexEarl/ironpython2/build/2.7.8.1-396/artifacts to see if it resolves your issue. Note that numpy will not install (and does not work with IronPython).

**Comment by JackandJazz** [comment] 2017-12-05 22:06
@slide Im sorry, didnt noticed that issue.
@slozier Thanks to you so much sir. That build worked nicely! Problem solved in <24h from posting. Ty all =)

code shown after installing:

C:\>ipy -X:Frames -m pip install fastkml
Collecting fastkml
C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:1: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  from __future__ import absolute_import
  Using cached fastkml-0.11.tar.gz
Collecting pygeoif (from fastkml)
  Using cached pygeoif-0.7.tar.gz
Collecting python-dateutil (from fastkml)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil->fastkml)
  Using cached six-1.11.0-py2.py3-none-any.whl
Installing collected packages: pygeoif, six, python-dateutil, fastkml
  Running setup.py install for pygeoif ... done
  Running setup.py install for fastkml ... done
Successfully installed fastkml-0.11 pygeoif-0.7 python-dateutil-2.6.1 six-1.11.0
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by slide** [comment] 2017-12-05 22:43
Fyi, with 2.7.8 you don't need the -X:Frames param anymore. We turned on frames by default since they are needed for so much.

**Comment by JackandJazz** [comment] 2017-12-07 12:09
Got it!

**Comment by shenh** [comment] 2018-06-24 02:36
Is there any plan in supporting numpy, scipy in IronPython? They are so widely used in python community for numerical computation. Also, what is the plan for supporting python 3x, considering many libs will end their support for 2x in a couple years. Thanks

**Comment by slide** [comment] 2018-06-24 03:38
It would be great to support them, one main issue is that they rely on module code written in C which relies on the C Python object model which we don't have. We'd have to implement all of the native pieces ourselves in C#

**Comment by slide** [comment] 2018-06-24 17:43
I really hope so!

**Comment by mehul009** [comment] 2018-11-12 13:35
please try to provide a numpy, scipy, pandas and other scientific modules on iron python.
it required for the open source process simulator dwsim and coco
([https://github.com/DanWBR/dwsim5]) for the custom unit operation which only supports IronPython, so we can make the high-level working model by using IronPython
